-- Calculate the total revenue generated by each category, from highest to lowest--
SELECT category, ROUND(SUM(transaction_amount),2) AS total_revenue
FROM creditcard.transaction
GROUP BY category
ORDER BY transaction_amount DESC;

-- Identify the top 5 customers with the highest transaction amounts --
SELECT CONCAT(name," ",surname) AS name, transaction_amount
FROM creditcard.transaction
ORDER BY transaction_amount DESC
LIMIT 5;

-- Analyze the average transaction amount by category, from lowest to highest --
SELECT category, ROUND(AVG(transaction_amount),2) AS avg_transaction_amount
FROM creditcard.transaction
GROUP BY category
ORDER BY transaction_amount;

-- Determine the 5 most frequently visited merchants --
SELECT merchant_name, COUNT(*) AS visit_count
FROM creditcard.transaction
GROUP BY merchant_name
ORDER BY visit_count DESC
LIMIT 5;

-- Calculate the revenue generated by the most visited merchant --
WITH MerchantVisits AS (
    SELECT merchant_name, COUNT(*) AS visit_count
    FROM creditcard.transaction
    GROUP BY merchant_name
    ORDER BY visit_count DESC
    LIMIT 1
)
SELECT merchant_name, ROUND(SUM(transaction_amount),2) AS revenue_generated
FROM creditcard.transaction
WHERE merchant_name = (SELECT merchant_name FROM MerchantVisits);

-- Find the top-spending customer in each category --
SELECT category, CONCAT(name," ",surname) AS name, MAX(transaction_amount) AS max_spending
FROM creditcard.transaction
GROUP BY category
ORDER BY max_spending DESC;
